server:
  port: 8081

spring:
  application:
    name: blog-pessoa-service
  datasource:
    url: jdbc:mysql://localhost:3306/blog-pessoas
    username: blog-pessoas
    password: ${DB_PASSWORD:mysql}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          lob:
            non-contextual-creation: true
  output:
    ansi:
      enabled: Always

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration-minutes: ${JWT_EXPIRATION_MINUTES:60}

